### PR TITLE
Provide new function EMPTY-TAG.

### PR DESCRIPTION
**Pull request by phmarek**

### CODE REVIEW

**Comment by phmarek** [comment]
Thanks, that was quick!

**Comment by VitoVan** [comment]
May I add you to the author list here?
https://github.com/VitoVan/xml-emitter/blob/master/xml-emitter.asd#L9

**Comment by phmarek** [comment]
Yes, of course.

**Comment by VitoVan** [comment]
Done.

Thank you Philipp Marek.

**Pull request merged**
